### ISSUE TITLE
overriding nginx's default handling of '/'

### ISSUE THREAD

**Issue by carlegbert** [jabbalaci/DigitalOceanFlask#1]
Hi! Thanks for your awesome tutorial.
I got my Flask app up and running and everything is working great, except it seems that the '/' route (as in 'http://\<ip-address\>' maps to a default file provided by nginx, which I believe was deleted as part of this tutorial. EG, I have the routes '/' and '/index' registered to a function in my flask app, but nginx is overriding '/' and returning a 404 (which is then being handled by the custom 404 error handler I provided in my flask app). However the '/index' route is being handled as expected. Is there some way to stop nginx from trying to provide a result for '/' and just let the flask application handle every route?
Sorry if this is a stupid question, I'm very new to nginx and webservers in general and I wasn't sure what to search stackoverflow/google for to fix it myself.
Thanks for your help!

**Comment by carlegbert** [comment]
Never mind- seems to have been a caching issue. Thanks again for this tutorial, it's great.

**Comment by jabbalaci** [comment]
OK, I'm glad it got resolved.
